function plotSpectrumFreq(signal, folderPath, label, torque, speed, channel,element)

    % Compute power spectrum

    % Generated by MATLAB(R) 24.1 and Signal Processing Toolbox 24.1.
    % Generated on: 19-Aug-2024 21:38:40
    
    % Parameters
    %frequencyLimits = [0 1]*pi; % Normalized frequency (rad/sample)
    
    %%
    % Index into signal time region of interest
    % timeLimits = [1 450000]; % samples
    % signal_ROI = signal(:);
    % signal_ROI = signal_ROI(timeLimits(1):timeLimits(2));

    % Parameters
    timeLimits = [0 44.9999]; % seconds
    frequencyLimits = [0 5000]; % Hz
    
    %%
    % Index into signal time region of interest
    signal_ROI = signal(:);
    sampleRate = 10000; % Hz
    startTime = 0; % seconds
    minIdx = ceil(max((timeLimits(1)-startTime)*sampleRate,0))+1;
    maxIdx = floor(min((timeLimits(2)-startTime)*sampleRate,length(signal_ROI)-1))+1;
    signal_ROI = signal_ROI(minIdx:maxIdx);
    
    % Create a new figure
    fig = figure;
    
    % Compute spectral estimate and plot the results
    pspectrum(signal_ROI,sampleRate, ...
    'FrequencyLimits',frequencyLimits);
    
    %title(['Torque: ', num2str(torque), 'Nm, Speed: ', num2str(speed), 'rpm, Channel: ', num2str(channel), ', Element: ', num2str(element)]);
    title('Fs: 10kHz')
    fileName = [num2str(torque),'Nm_',num2str(speed),'rpm_ch', num2str(channel), '_', num2str(element)]
    targetPath = fullfile(folderPath, string(fileName));
    disp(targetPath)
    % Save the plot to the specified target path as a PNG
    saveas(fig, targetPath, 'png');
    
    % Close the figure to prevent it from displaying
    close(fig);

end